//! 项目注册表 — 所有项目/SDK/工具/服务的动态定义。
//!
//! 支持从文件 `%USERPROFILE%\.any-version\sdks_registry.json` 加载。
//! 如果文件不存在，会自动创建默认的设置文件。

use serde_json;
use super::types::{ProjectDef, ProjectCategory, EnvVarDef, FindRule, ResolvePattern, MirrorOption};

/// 全局项目注册表
pub fn registry() -> Vec<ProjectDef> {
    load_registry()
}

/// 从配置文件动态加载注册表
pub fn load_registry() -> Vec<ProjectDef> {
    let base_dir = crate::commands::config::get_base_dir();
    let registry_path = base_dir.join("sdks_registry.json");
    if registry_path.exists() {
        if let Ok(data) = std::fs::read_to_string(&registry_path) {
            if let Ok(list) = serde_json::from_str::<Vec<ProjectDef>>(&data) {
                // 如果已存的默认服务项缺少字段，强制重新生成
                let needs_regeneration = list.iter().any(|s| {
                    (s.id == "mysql" || s.id == "redis" || s.id == "nginx") && !s.is_service
                });
                if !needs_regeneration {
                    return list;
                }
            }
        }
    }
    // 不存在或解析错误则写入默认列表
    let defaults = get_default_registry();
    let _ = std::fs::create_dir_all(&base_dir);
    if let Ok(data) = serde_json::to_string_pretty(&defaults) {
        let _ = std::fs::write(&registry_path, data);
    }
    defaults
}

/// 根据 id 查找项目定义
pub fn find_by_id(id: &str) -> Option<ProjectDef> {
    registry().into_iter().find(|s| s.id == id)
}

/// 返回所有项目 id 列表
pub fn all_ids() -> Vec<String> {
    registry().into_iter().map(|s| s.id).collect()
}

/// 返回默认的项目注册表（22 种 SDK）
pub fn get_default_registry() -> Vec<ProjectDef> {
    vec![
        // ─── 开发语言 ───
        ProjectDef {
            id: "nodejs".to_string(),
            display_name: "Node.js".to_string(),
            category: ProjectCategory::Language,
            official_website: "https://nodejs.org".to_string(),
            icon: "nodejs".to_string(),
            env_vars: vec![
                EnvVarDef { name: "NODE_PATH".to_string(), desc: "全局模块搜索路径".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "NPM_CONFIG_PREFIX".to_string(), desc: "npm 全局安装前缀".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "NPM_CONFIG_CACHE".to_string(), desc: "npm 缓存目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "NVM_DIR".to_string(), desc: "nvm-windows 安装目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "NVM_HOME".to_string(), desc: "nvm-windows 根目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "VOLTA_HOME".to_string(), desc: "Volta 安装目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "NVM_HOME".to_string(), bin_sub: "".to_string(), exe_name: "node.exe".to_string() }, source_label: "nvm-windows".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "VOLTA_HOME".to_string(), bin_sub: "bin".to_string(), exe_name: "node.exe".to_string() }, source_label: "Volta".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\nodejs".to_string(), exe_name: "node.exe".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "chocolatey\\lib\\nodejs".to_string(), exe_name: "node.exe".to_string() }, source_label: "Chocolatey".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\msys64\\mingw64\\bin".to_string(), exe_name: "node.exe".to_string() }, source_label: "MSYS2".to_string(), priority: 60, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\nodejs".to_string(), exe_name: "node.exe".to_string() }, source_label: "Program Files".to_string(), priority: 70, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\nodejs\\".to_string(), exe_name: "node.exe".to_string() }, source_label: "系统 PATH".to_string(), priority: 80, root_offset: 1 },
            ],
            has_cache: true,
            cache_detect_cmd: Some("npm config get cache".to_string()),
            cache_default_path: None,
            has_mirror: true,
            mirror_options: Some(vec![
                MirrorOption { mirror_type: "npm".to_string(), name: "淘宝 NPM 镜像".to_string(), url: "https://registry.npmmirror.com".to_string() },
            ]),
            has_pkg: true,
            pkg_manager: Some("npm".to_string()),
            pkg_homepage_template: Some("https://www.npmjs.com/package/{pkg}".to_string()),
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "go".to_string(),
            display_name: "Go".to_string(),
            category: ProjectCategory::Language,
            official_website: "https://go.dev".to_string(),
            icon: "go".to_string(),
            env_vars: vec![
                EnvVarDef { name: "GOROOT".to_string(), desc: "Go 安装根目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "GOPATH".to_string(), desc: "Go 工作区路径".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "GOBIN".to_string(), desc: "Go 二进制安装目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "GOCACHE".to_string(), desc: "Go 构建缓存目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "GOPROXY".to_string(), desc: "Go 模块代理地址".to_string(), check_type: "nonempty".to_string() },
                EnvVarDef { name: "GONOSUMDB".to_string(), desc: "跳过 sum 校验模块列表".to_string(), check_type: "nonempty".to_string() },
                EnvVarDef { name: "GONOSUMCHECK".to_string(), desc: "跳过校验模块列表".to_string(), check_type: "nonempty".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "GOROOT".to_string(), bin_sub: "bin".to_string(), exe_name: "go.exe".to_string() }, source_label: "环境变量 GOROOT".to_string(), priority: 5, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\go".to_string(), exe_name: "go.exe".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "chocolatey\\lib\\golang".to_string(), exe_name: "go.exe".to_string() }, source_label: "Chocolatey".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\Go\\bin".to_string(), exe_name: "go.exe".to_string() }, source_label: "Program Files".to_string(), priority: 70, root_offset: 1 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\go\\bin".to_string(), exe_name: "go.exe".to_string() }, source_label: "系统 PATH".to_string(), priority: 80, root_offset: 1 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Users".to_string(), exe_name: "go.exe".to_string() }, source_label: "用户目录".to_string(), priority: 90, root_offset: 0 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: true,
            mirror_options: Some(vec![
                MirrorOption { mirror_type: "goproxy".to_string(), name: "七牛 Goproxy".to_string(), url: "https://goproxy.cn".to_string() },
            ]),
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "python".to_string(),
            display_name: "Python".to_string(),
            category: ProjectCategory::Language,
            official_website: "https://www.python.org".to_string(),
            icon: "python".to_string(),
            env_vars: vec![
                EnvVarDef { name: "PYTHONHOME".to_string(), desc: "Python 解释器根目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "PYTHONPATH".to_string(), desc: "Python 模块搜索路径".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "PIP_CACHE_DIR".to_string(), desc: "pip 缓存目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "CONDA_PREFIX".to_string(), desc: "conda 环境目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "PYENV_ROOT".to_string(), desc: "pyenv-win 根目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "CONDA_PREFIX".to_string(), bin_sub: "".to_string(), exe_name: "python.exe".to_string() }, source_label: "conda".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "PYENV_ROOT".to_string(), bin_sub: "pyenv-win\\shims".to_string(), exe_name: "python.exe".to_string() }, source_label: "pyenv-win".to_string(), priority: 15, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\python".to_string(), exe_name: "python.exe".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "chocolatey\\lib\\python".to_string(), exe_name: "python.exe".to_string() }, source_label: "Chocolatey".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\msys64\\mingw64\\bin".to_string(), exe_name: "python.exe".to_string() }, source_label: "MSYS2".to_string(), priority: 60, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\Python313".to_string(), exe_name: "python.exe".to_string() }, source_label: "Program Files".to_string(), priority: 70, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\Python312".to_string(), exe_name: "python.exe".to_string() }, source_label: "Program Files".to_string(), priority: 70, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\Python311".to_string(), exe_name: "python.exe".to_string() }, source_label: "Program Files".to_string(), priority: 70, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\Python310".to_string(), exe_name: "python.exe".to_string() }, source_label: "Program Files".to_string(), priority: 70, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\python3".to_string(), exe_name: "python.exe".to_string() }, source_label: "系统 PATH".to_string(), priority: 80, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\python2".to_string(), exe_name: "python.exe".to_string() }, source_label: "系统 PATH".to_string(), priority: 80, root_offset: 0 },
            ],
            has_cache: true,
            cache_detect_cmd: Some("pip cache dir".to_string()),
            cache_default_path: None,
            has_mirror: true,
            mirror_options: Some(vec![
                MirrorOption { mirror_type: "pypi".to_string(), name: "清华 PyPI 镜像".to_string(), url: "https://pypi.tuna.tsinghua.edu.cn/simple".to_string() },
                MirrorOption { mirror_type: "pypi".to_string(), name: "阿里云 PyPI 镜像".to_string(), url: "https://mirrors.aliyun.com/pypi/simple".to_string() },
            ]),
            has_pkg: true,
            pkg_manager: Some("pip".to_string()),
            pkg_homepage_template: Some("https://pypi.org/project/{pkg}".to_string()),
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "java".to_string(),
            display_name: "Java".to_string(),
            category: ProjectCategory::Language,
            official_website: "https://adoptium.net".to_string(),
            icon: "java".to_string(),
            env_vars: vec![
                EnvVarDef { name: "JAVA_HOME".to_string(), desc: "JDK 安装根目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "JDK_HOME".to_string(), desc: "JDK 根目录（替代变量）".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "JRE_HOME".to_string(), desc: "JRE 根目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "CLASSPATH".to_string(), desc: "Java 类库搜索路径".to_string(), check_type: "nonempty".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "JAVA_HOME".to_string(), bin_sub: "bin".to_string(), exe_name: "java.exe".to_string() }, source_label: "环境变量 JAVA_HOME".to_string(), priority: 5, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\temurin".to_string(), exe_name: "java.exe".to_string() }, source_label: "Scoop (Temurin)".to_string(), priority: 40, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\corretto".to_string(), exe_name: "java.exe".to_string() }, source_label: "Scoop (Corretto)".to_string(), priority: 40, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\openjdk".to_string(), exe_name: "java.exe".to_string() }, source_label: "Scoop (OpenJDK)".to_string(), priority: 40, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\zulu".to_string(), exe_name: "java.exe".to_string() }, source_label: "Scoop (Zulu)".to_string(), priority: 40, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\liberica".to_string(), exe_name: "java.exe".to_string() }, source_label: "Scoop (Liberica)".to_string(), priority: 40, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "chocolatey\\lib\\temurin".to_string(), exe_name: "java.exe".to_string() }, source_label: "Chocolatey".to_string(), priority: 40, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "chocolatey\\lib\\corretto".to_string(), exe_name: "java.exe".to_string() }, source_label: "Chocolatey".to_string(), priority: 40, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "chocolatey\\lib\\jdk".to_string(), exe_name: "java.exe".to_string() }, source_label: "Chocolatey".to_string(), priority: 40, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\Eclipse Adoptium".to_string(), exe_name: "java.exe".to_string() }, source_label: "Adoptium".to_string(), priority: 60, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\Eclipse Foundation".to_string(), exe_name: "java.exe".to_string() }, source_label: "Eclipse".to_string(), priority: 60, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\Java".to_string(), exe_name: "java.exe".to_string() }, source_label: "Program Files\\Java".to_string(), priority: 65, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\Amazon Corretto".to_string(), exe_name: "java.exe".to_string() }, source_label: "Amazon Corretto".to_string(), priority: 60, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\Zulu".to_string(), exe_name: "java.exe".to_string() }, source_label: "Azul Zulu".to_string(), priority: 60, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\Microsoft".to_string(), exe_name: "java.exe".to_string() }, source_label: "Microsoft JDK".to_string(), priority: 60, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\msys64\\mingw64\\bin".to_string(), exe_name: "java.exe".to_string() }, source_label: "MSYS2".to_string(), priority: 70, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\java\\jdk".to_string(), exe_name: "java.exe".to_string() }, source_label: "系统 PATH".to_string(), priority: 80, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\java\\jre".to_string(), exe_name: "java.exe".to_string() }, source_label: "系统 PATH".to_string(), priority: 80, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\adoptium".to_string(), exe_name: "java.exe".to_string() }, source_label: "系统 PATH".to_string(), priority: 80, root_offset: 0 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "flutter".to_string(),
            display_name: "Flutter".to_string(),
            category: ProjectCategory::Language,
            official_website: "https://flutter.dev".to_string(),
            icon: "flutter".to_string(),
            env_vars: vec![
                EnvVarDef { name: "FLUTTER_ROOT".to_string(), desc: "Flutter SDK 根目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "FLUTTER_STORAGE_BASE_URL".to_string(), desc: "Flutter 引擎下载 URL".to_string(), check_type: "nonempty".to_string() },
                EnvVarDef { name: "PUB_HOSTED_URL".to_string(), desc: "Dart pub 包仓库地址".to_string(), check_type: "nonempty".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "FLUTTER_ROOT".to_string(), bin_sub: "bin".to_string(), exe_name: "flutter.bat".to_string() }, source_label: "环境变量 FLUTTER_ROOT".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\flutter".to_string(), exe_name: "flutter.bat".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "chocolatey\\lib\\flutter".to_string(), exe_name: "flutter.bat".to_string() }, source_label: "Chocolatey".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\flutter\\bin".to_string(), exe_name: "flutter.bat".to_string() }, source_label: "C:\\flutter".to_string(), priority: 60, root_offset: 1 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\src\\flutter\\bin".to_string(), exe_name: "flutter.bat".to_string() }, source_label: "C:\\src\\flutter".to_string(), priority: 60, root_offset: 1 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\flutter\\bin".to_string(), exe_name: "flutter.bat".to_string() }, source_label: "系统 PATH".to_string(), priority: 80, root_offset: 1 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: true,
            mirror_options: Some(vec![
                MirrorOption { mirror_type: "flutter_storage".to_string(), name: "Flutter 中国镜像".to_string(), url: "https://storage.flutter-io.cn".to_string() },
                MirrorOption { mirror_type: "pub_hosted".to_string(), name: "Dart Pub 中国镜像".to_string(), url: "https://pub.flutter-io.cn".to_string() },
            ]),
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "rust".to_string(),
            display_name: "Rust".to_string(),
            category: ProjectCategory::Language,
            official_website: "https://www.rust-lang.org".to_string(),
            icon: "rust".to_string(),
            env_vars: vec![
                EnvVarDef { name: "CARGO_HOME".to_string(), desc: "Cargo 包管理器目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "RUSTUP_HOME".to_string(), desc: "Rustup 工具链目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "CARGO_TARGET_DIR".to_string(), desc: "Cargo 构建输出目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "RUSTUP_HOME".to_string(), bin_sub: "".to_string(), exe_name: "rustc.exe".to_string() }, source_label: "rustup".to_string(), priority: 5, root_offset: 0 },
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "CARGO_HOME".to_string(), bin_sub: "bin".to_string(), exe_name: "rustc.exe".to_string() }, source_label: "Cargo".to_string(), priority: 8, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\rustup".to_string(), exe_name: "rustc.exe".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "chocolatey\\lib\\rust".to_string(), exe_name: "rustc.exe".to_string() }, source_label: "Chocolatey".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\msys64\\mingw64\\bin".to_string(), exe_name: "rustc.exe".to_string() }, source_label: "MSYS2".to_string(), priority: 60, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\.cargo\\bin".to_string(), exe_name: "rustc.exe".to_string() }, source_label: ".cargo\\bin".to_string(), priority: 50, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\rustup\\".to_string(), exe_name: "rustc.exe".to_string() }, source_label: "rustup".to_string(), priority: 55, root_offset: 0 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: true,
            mirror_options: Some(vec![
                MirrorOption { mirror_type: "crates".to_string(), name: "字节跳动 RsProxy".to_string(), url: "https://rsproxy.cn".to_string() },
                MirrorOption { mirror_type: "crates".to_string(), name: "中科大镜像".to_string(), url: "https://mirrors.ustc.edu.cn/crates.io-index".to_string() },
            ]),
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "bun".to_string(),
            display_name: "Bun".to_string(),
            category: ProjectCategory::Language,
            official_website: "https://bun.sh".to_string(),
            icon: "bun".to_string(),
            env_vars: vec![
                EnvVarDef { name: "BUN_INSTALL".to_string(), desc: "Bun 安装根目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "BUN_INSTALL".to_string(), bin_sub: "bin".to_string(), exe_name: "bun.exe".to_string() }, source_label: "环境变量 BUN_INSTALL".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\bun".to_string(), exe_name: "bun.exe".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\.bun\\bin".to_string(), exe_name: "bun.exe".to_string() }, source_label: ".bun\\bin".to_string(), priority: 50, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Users".to_string(), exe_name: "bun.exe".to_string() }, source_label: "用户目录".to_string(), priority: 90, root_offset: 0 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        // ─── 库管理工具 ───
        ProjectDef {
            id: "maven".to_string(),
            display_name: "Maven".to_string(),
            category: ProjectCategory::Language,
            official_website: "https://maven.apache.org".to_string(),
            icon: "maven".to_string(),
            env_vars: vec![
                EnvVarDef { name: "MAVEN_HOME".to_string(), desc: "Maven 安装根目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "M2_HOME".to_string(), desc: "Maven 根目录（旧版本）".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "MAVEN_HOME".to_string(), bin_sub: "bin".to_string(), exe_name: "mvn.cmd".to_string() }, source_label: "环境变量 MAVEN_HOME".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\maven".to_string(), exe_name: "mvn.cmd".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\apache-maven\\bin".to_string(), exe_name: "mvn.cmd".to_string() }, source_label: "系统 PATH".to_string(), priority: 80, root_offset: 1 },
            ],
            has_cache: true,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: true,
            mirror_options: Some(vec![
                MirrorOption { mirror_type: "maven_central".to_string(), name: "阿里云 Maven 镜像".to_string(), url: "https://maven.aliyun.com/repository/public".to_string() },
            ]),
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "gradle".to_string(),
            display_name: "Gradle".to_string(),
            category: ProjectCategory::Language,
            official_website: "https://gradle.org".to_string(),
            icon: "gradle".to_string(),
            env_vars: vec![
                EnvVarDef { name: "GRADLE_HOME".to_string(), desc: "Gradle 安装目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "GRADLE_USER_HOME".to_string(), desc: "Gradle 用户数据目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "GRADLE_HOME".to_string(), bin_sub: "bin".to_string(), exe_name: "gradle.bat".to_string() }, source_label: "环境变量 GRADLE_HOME".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\gradle".to_string(), exe_name: "gradle.bat".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\gradle\\bin".to_string(), exe_name: "gradle.bat".to_string() }, source_label: "系统 PATH".to_string(), priority: 80, root_offset: 1 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "yarn".to_string(),
            display_name: "Yarn".to_string(),
            category: ProjectCategory::Language,
            official_website: "https://yarnpkg.com".to_string(),
            icon: "yarn".to_string(),
            env_vars: vec![],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\yarn".to_string(), exe_name: "yarn.cmd".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\.yarn\\bin".to_string(), exe_name: "yarn.cmd".to_string() }, source_label: ".yarn\\bin".to_string(), priority: 50, root_offset: 0 },
            ],
            has_cache: true,
            cache_detect_cmd: Some("yarn cache dir".to_string()),
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "pnpm".to_string(),
            display_name: "pnpm".to_string(),
            category: ProjectCategory::Language,
            official_website: "https://pnpm.io".to_string(),
            icon: "pnpm".to_string(),
            env_vars: vec![],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\pnpm".to_string(), exe_name: "pnpm.exe".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\.pnpm\\".to_string(), exe_name: "pnpm.exe".to_string() }, source_label: ".pnpm".to_string(), priority: 50, root_offset: 0 },
            ],
            has_cache: true,
            cache_detect_cmd: Some("pnpm store path".to_string()),
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "nuget".to_string(),
            display_name: "NuGet".to_string(),
            category: ProjectCategory::Language,
            official_website: "https://www.nuget.org".to_string(),
            icon: "nuget".to_string(),
            env_vars: vec![
                EnvVarDef { name: "NUGET_PACKAGES".to_string(), desc: "NuGet 全局包缓存目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\.nuget\\packages".to_string(), exe_name: "nuget.exe".to_string() }, source_label: "NuGet cache".to_string(), priority: 80, root_offset: 0 },
            ],
            has_cache: true,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        // ─── 本地服务 ───
        ProjectDef {
            id: "nginx".to_string(),
            display_name: "Nginx".to_string(),
            category: ProjectCategory::Service,
            official_website: "https://nginx.org".to_string(),
            icon: "nginx".to_string(),
            env_vars: vec![
                EnvVarDef { name: "NGINX_HOME".to_string(), desc: "Nginx 安装根目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\nginx".to_string(), exe_name: "nginx.exe".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "chocolatey\\lib\\nginx".to_string(), exe_name: "nginx.exe".to_string() }, source_label: "Chocolatey".to_string(), priority: 40, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\nginx".to_string(), exe_name: "nginx.exe".to_string() }, source_label: "C:\\nginx".to_string(), priority: 60, root_offset: 0 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: true,
            default_port: Some(80),
            data_dir: Some("html".to_string()),
            log_dir: Some("logs".to_string()),
            config_file: Some("conf\\nginx.conf".to_string()),
            start_cmd: Some("nginx.exe".to_string()),
            stop_cmd: Some("nginx.exe -s stop".to_string()),
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "redis".to_string(),
            display_name: "Redis".to_string(),
            category: ProjectCategory::Service,
            official_website: "https://redis.io".to_string(),
            icon: "redis".to_string(),
            env_vars: vec![
                EnvVarDef { name: "REDIS_HOME".to_string(), desc: "Redis 安装根目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "REDIS_HOME".to_string(), bin_sub: "".to_string(), exe_name: "redis-server.exe".to_string() }, source_label: "环境变量 REDIS_HOME".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\redis".to_string(), exe_name: "redis-server.exe".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 0 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\redis".to_string(), exe_name: "redis-server.exe".to_string() }, source_label: "C:\\redis".to_string(), priority: 60, root_offset: 0 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: true,
            default_port: Some(6379),
            data_dir: Some(".".to_string()),
            log_dir: Some(".".to_string()),
            config_file: Some("redis.windows.conf".to_string()),
            start_cmd: Some("redis-server.exe".to_string()),
            stop_cmd: Some("redis-cli.exe shutdown".to_string()),
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "mysql".to_string(),
            display_name: "MySQL".to_string(),
            category: ProjectCategory::Service,
            official_website: "https://www.mysql.com".to_string(),
            icon: "mysql".to_string(),
            env_vars: vec![
                EnvVarDef { name: "MYSQL_HOME".to_string(), desc: "MySQL 安装根目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "MYSQL_HOME".to_string(), bin_sub: "bin".to_string(), exe_name: "mysql.exe".to_string() }, source_label: "环境变量 MYSQL_HOME".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\mysql".to_string(), exe_name: "mysql.exe".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\MySQL\\MySQL Server".to_string(), exe_name: "mysql.exe".to_string() }, source_label: "Program Files".to_string(), priority: 70, root_offset: 1 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: true,
            default_port: Some(3306),
            data_dir: Some("data".to_string()),
            log_dir: Some("data".to_string()),
            config_file: Some("my.ini".to_string()),
            start_cmd: Some("bin\\mysqld.exe --defaults-file=my.ini --console".to_string()),
            stop_cmd: Some("bin\\mysqladmin.exe -u root shutdown".to_string()),
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "mongodb".to_string(),
            display_name: "MongoDB".to_string(),
            category: ProjectCategory::Service,
            official_website: "https://www.mongodb.com".to_string(),
            icon: "mongodb".to_string(),
            env_vars: vec![
                EnvVarDef { name: "MONGO_HOME".to_string(), desc: "MongoDB 安装根目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "MONGO_HOME".to_string(), bin_sub: "bin".to_string(), exe_name: "mongod.exe".to_string() }, source_label: "环境变量 MONGO_HOME".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\mongodb".to_string(), exe_name: "mongod.exe".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\MongoDB\\Server".to_string(), exe_name: "mongod.exe".to_string() }, source_label: "Program Files".to_string(), priority: 70, root_offset: 1 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: true,
            default_port: Some(27017),
            data_dir: Some("data".to_string()),
            log_dir: Some("mongod.log".to_string()),
            config_file: None,
            start_cmd: Some("bin\\mongod.exe --port 27017 --dbpath data".to_string()),
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "postgresql".to_string(),
            display_name: "PostgreSQL".to_string(),
            category: ProjectCategory::Service,
            official_website: "https://www.postgresql.org".to_string(),
            icon: "postgresql".to_string(),
            env_vars: vec![
                EnvVarDef { name: "PGDATA".to_string(), desc: "PostgreSQL 数据目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "PGHOME".to_string(), desc: "PostgreSQL 安装根目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "PGHOME".to_string(), bin_sub: "bin".to_string(), exe_name: "psql.exe".to_string() }, source_label: "环境变量 PGHOME".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\postgresql".to_string(), exe_name: "psql.exe".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\PostgreSQL".to_string(), exe_name: "psql.exe".to_string() }, source_label: "Program Files".to_string(), priority: 70, root_offset: 1 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: true,
            default_port: Some(5432),
            data_dir: Some("data".to_string()),
            log_dir: Some("logfile".to_string()),
            config_file: None,
            start_cmd: Some("bin\\pg_ctl.exe -D data -l logfile start".to_string()),
            stop_cmd: Some("bin\\pg_ctl.exe -D data stop".to_string()),
            download_url_template: None,
            remote_versions_url: None,
        },
        // ─── 开发工具 ───
        ProjectDef {
            id: "android".to_string(),
            display_name: "Android SDK".to_string(),
            category: ProjectCategory::Tool,
            official_website: "https://developer.android.com".to_string(),
            icon: "android".to_string(),
            env_vars: vec![
                EnvVarDef { name: "ANDROID_HOME".to_string(), desc: "Android SDK 根目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "ANDROID_SDK_ROOT".to_string(), desc: "Android SDK 根目录（旧版本）".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "ANDROID_SDK_HOME".to_string(), desc: "Android 用户数据目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "ANDROID_NDK_HOME".to_string(), desc: "Android NDK 目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "ANDROID_PREFS_ROOT".to_string(), desc: "Android 偏好设置目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "NDK_HOME".to_string(), desc: "NDK 根目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "ANDROID_HOME".to_string(), bin_sub: "cmdline-tools\\latest\\bin".to_string(), exe_name: "sdkmanager.bat".to_string() }, source_label: "环境变量 ANDROID_HOME".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\android-sdk".to_string(), exe_name: "sdkmanager.bat".to_string() }, source_label: "系统 PATH".to_string(), priority: 80, root_offset: 0 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "harmony".to_string(),
            display_name: "鸿蒙 HarmonyOS".to_string(),
            category: ProjectCategory::Tool,
            official_website: "https://developer.huawei.com/consumer/cn/harmony/".to_string(),
            icon: "harmony".to_string(),
            env_vars: vec![
                EnvVarDef { name: "OHOS_SDK_HOME".to_string(), desc: "鸿蒙 SDK 根目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "OHOS_SDK_HOME".to_string(), bin_sub: "bin".to_string(), exe_name: "ohpm.bat".to_string() }, source_label: "环境变量 OHOS_SDK_HOME".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\ohpm\\bin".to_string(), exe_name: "ohpm.bat".to_string() }, source_label: "系统 PATH".to_string(), priority: 80, root_offset: 0 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "cuda".to_string(),
            display_name: "CUDA Toolkit".to_string(),
            category: ProjectCategory::Tool,
            official_website: "https://developer.nvidia.com/cuda-toolkit".to_string(),
            icon: "cuda".to_string(),
            env_vars: vec![
                EnvVarDef { name: "CUDA_PATH".to_string(), desc: "CUDA Toolkit 安装目录".to_string(), check_type: "path".to_string() },
                EnvVarDef { name: "CUDA_HOME".to_string(), desc: "CUDA Toolkit 根目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "CUDA_PATH".to_string(), bin_sub: "bin".to_string(), exe_name: "nvcc.exe".to_string() }, source_label: "环境变量 CUDA_PATH".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\cuda".to_string(), exe_name: "nvcc.exe".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::FixedPath { path: "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA".to_string(), exe_name: "nvcc.exe".to_string() }, source_label: "NVIDIA GPU".to_string(), priority: 60, root_offset: 1 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
        ProjectDef {
            id: "ffmpeg".to_string(),
            display_name: "FFmpeg".to_string(),
            category: ProjectCategory::Tool,
            official_website: "https://ffmpeg.org".to_string(),
            icon: "ffmpeg".to_string(),
            env_vars: vec![
                EnvVarDef { name: "FFMPEG_HOME".to_string(), desc: "FFmpeg 安装目录".to_string(), check_type: "path".to_string() },
            ],
            find_rules: vec![
                FindRule { pattern: ResolvePattern::EnvBin { env_var: "FFMPEG_HOME".to_string(), bin_sub: "bin".to_string(), exe_name: "ffmpeg.exe".to_string() }, source_label: "环境变量 FFMPEG_HOME".to_string(), priority: 10, root_offset: 0 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "scoop\\apps\\ffmpeg".to_string(), exe_name: "ffmpeg.exe".to_string() }, source_label: "Scoop".to_string(), priority: 40, root_offset: 1 },
                FindRule { pattern: ResolvePattern::PathContains { path_key: "\\ffmpeg\\".to_string(), exe_name: "ffmpeg.exe".to_string() }, source_label: "系统 PATH".to_string(), priority: 80, root_offset: 1 },
            ],
            has_cache: false,
            cache_detect_cmd: None,
            cache_default_path: None,
            has_mirror: false,
            mirror_options: None,
            has_pkg: false,
            pkg_manager: None,
            pkg_homepage_template: None,
            is_service: false,
            default_port: None,
            data_dir: None,
            log_dir: None,
            config_file: None,
            start_cmd: None,
            stop_cmd: None,
            download_url_template: None,
            remote_versions_url: None,
        },
    ]
}
